"""new tables

Revision ID: f4d6c6ab69e4
Revises: 
Create Date: 2025-10-03 19:19:10.945818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d6c6ab69e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('game_players_game_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('game_players_player_id_fkey')),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name=op.f('game_players_pkey'))
    )
    # ### end Alembic commands ###
